# This is a basic workflow to help you get started with Actions

name: Meeting Minutes

permissions:
  contents: write

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Create a new branch and push it
        run: |
          git config user.name "Meeting-Bot"
          git config user.email ciro.miranda@flutter.com
          git checkout -b "meeting-$(date +'%Y-%m-%d')"
          cp meeting-minutes-template.md meetings/meeting-$(date +'%Y-%m-%d').md
          git add meetings/meeting-$(date +'%Y-%m-%d').md
          git commit -m "Meeting meeting-$(date +'%Y-%m-%d') created"
          git push origin "meeting-$(date +'%Y-%m-%d')"
